search:
  algorithm: aizynthfinder.search.retrostar.search_tree.SearchTree
  max_transforms: 5
  iteration_limit: 25000
  return_first: true
  time_limit: 15
  retro_bm_width: 16
  exclude_target_from_stock: true
  algorithm_config:
    use_prior: true
    prune_cycles_in_search: true
    immediate_instantiation: [transformer]

expansion:
  transformer:
    type: aizynthfinder.context.policy.extra_expansion_strategies.ModelZooExpansionStrategy
    gpu_mode: true
    data:
      module_path: single_step_retro/model/autoregressive
      kwargs:
        sampling: beam_search
        checkpoint_path: checkpoints/single_step_retrosynthesis/ss_transformer_checkpoint.ckpt
        vocab_path: checkpoints/single_step_retrosynthesis/vocab.json
        embedding_dim: 256
        feedforward_dim: 2048
        num_encoder_layers: 6
        num_decoder_layers: 6
        num_heads: 8
        activation: relu
        max_size: 200
        beam_size: 1
stock:
  paroutes: paroutes_stock.hdf5